#define ESP_INTR_FLAG_DEFAULT 0

#define BUTTON_BACK_STOP_PIN 18 // 15 (esp) || 33 (esp-mini)
#define BUTTON_BACK_STOP_SEL 1ULL << BUTTON_BACK_STOP_PIN

#define BUTTON_TOUCH_PIN 5 // 15 (esp) || 33 (esp-mini)
#define BUTTON_TOUCH_SEL 1ULL << BUTTON_BACK_STOP_PIN

#define LED_PIN 17
#define LED_SEL 1ULL << LED_PIN

#define OPTICAL_SWITCH_PIN 7
#define OPTICAL_SWITCH_SEL 1ULL << OPTICAL_SWITCH_PIN

#define STEP_MOTOR_NSLEEP_PIN 45 // EN = 0 (esp) || 16 (esp-mini)
#define STEP_MOTOR_NSLEEP_SEL 1ULL << STEP_MOTOR_NSLEEP_PIN

#define STEP_MOTOR_ENABLE_PIN 48 // EN = 0 (esp) || 16 (esp-mini)
#define STEP_MOTOR_ENABLE_SEL 1ULL << STEP_MOTOR_ENABLE_PIN

#define STEP_MOTOR_DIR_PIN 21 // DIR = 12 (esp) || 25 (esp-mini)
#define STEP_MOTOR_DIR_SEL 1ULL << STEP_MOTOR_DIR_PIN

#define STEP_MOTOR_STEP_PIN 47 // STEP = 14 (esp) || 22 (esp-mini)
#define STEP_MOTOR_STEP_SEL 1ULL << STEP_MOTOR_STEP_PIN

#define STEP_MOTOR_ENABLE_LEVEL 0 // EN = 1 (esp) || 0 (esp-mini)
#define STEP_MOTOR_DISABLE_LEVEL !STEP_MOTOR_ENABLE_LEVEL

#define STEP_MOTOR_SPIN_DIR_OUT 0
#define STEP_MOTOR_SPIN_DIR_IN !STEP_MOTOR_SPIN_DIR_OUT

#define STEP_MOTOR_M0_PIN 13
#define STEP_MOTOR_M0_SEL 1ULL << STEP_MOTOR_M0_PIN

#define STEP_MOTOR_M1_PIN 14
#define STEP_MOTOR_M1_SEL 1ULL << STEP_MOTOR_M1_PIN


#define STEP_MOTOR_RESOLUTION_HZ 1000000 // 1MHz resolution